name: Reusable workflow user
on:
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello,world!
        
  calling-called-workflow1:
    #needs: do-it
    uses: Thirthavathi-NR/called/.github/workflows/workflow1.yml@main
       
  calling-called-workflow2:
    uses: Thirthavathi-NR/called/.github/workflows/workflow2.yml@main
    
  calling-called-workflow3:
    needs: calling-called-workflow1
    uses: Thirthavathi-NR/caller/.github/workflows/workflow3.yml@main
  

