name: Reusable workflow user
on:
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello,world!
        
  calling-called:
    uses: Thirthavathi-NR/called/.github/workflows/main.yml@main
  
  calling-called2:  
    uses: Thirthavathi-NR/called/.github/workflows/workflow2.yml@main
